### ISSUE TITLE
Wrong Name

### ISSUE THREAD

**Issue by BakaPixel** [Oku-Jo/simpletarot#1]
I have it on good authority that is not the proper name for that person in the `simplereader.py` file.

Change should be `Baka` -> `Nova`

https://github.com/Oku-Jo/simpletarot/blob/9e6d93e7c761429de699b15c4fb17d2bb6174890/simplereader.py#L3

**Comment by Oku-Jo** [comment]
100%, i was wrong, it has been updated.
